# NumPy基础：数组和⽮量计算
#### p114

In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
# 功能：通过 rc 方法全局设置图形参数。
# "figure"：指定配置对象为图形（Figure）。
# figsize=(10, 6)：设置默认图形宽度为 10 英寸，高度为 6 英寸。
# 效果：之后所有 plt.figure() 或 plt.subplots() 生成的图形都会继承此尺寸，无需重复指定。
np.set_printoptions(precision=4, suppress=True)
# 功能：配置 NumPy 数组的打印行为。
# precision=4：浮点数显示 4 位小数（如 3.1416）。
# suppress=True：禁用科学计数法（如 0.0001 而非 1e-4）。
# 用途：提升 Jupyter Notebook 或控制台中数组输出的可读性。

In [1]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

1.7 ms ± 80.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
59.8 ms ± 1.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


##  NumPy的ndarray：⼀种多维数组对象
#### p116

In [4]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

In [5]:
data * 10
data + data

In [6]:
data.shape
data.dtype

## 创建ndarray
#### p118

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

In [9]:
arr2.ndim
arr2.shape

In [10]:
arr1.dtype
arr2.dtype

In [11]:
np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))

In [12]:
np.arange(15)

![表4-1 数组创建函数](./表4-1_数组创建函数.png)

## ndarray的数据类型
#### p120

In [13]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

![表4-2_numpy数据类型](./表4-2_numpy数据类型.png)

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr
float_arr.dtype

In [15]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

In [16]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)

In [17]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

In [18]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

## NumPy数组的运算
#### p123

In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

In [20]:
1 / arr
arr ** 2

In [21]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

## 基本的索引和切⽚
#### p125

In [22]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

In [23]:
arr_slice = arr[5:8]
arr_slice

In [24]:
arr_slice[1] = 12345
arr

In [25]:
arr_slice[:] = 64
arr

In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

In [27]:
arr2d[0][2]
arr2d[0, 2]

In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

In [29]:
arr3d[0]

In [30]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

In [31]:
arr3d[1, 0]

In [32]:
x = arr3d[1]
x
x[0]

## 切⽚索引
#### p129


In [33]:
arr
arr[1:6]

In [34]:
arr2d
arr2d[:2]

In [35]:
arr2d[:2, 1:]

In [36]:
lower_dim_slice = arr2d[1, :2]

In [37]:
lower_dim_slice.shape

In [38]:
arr2d[:2, 2]

In [39]:
arr2d[:, :1]

In [40]:
arr2d[:2, 1:] = 0
arr2d

![图4-2 ⼆维数组切⽚](./图4-2_⼆维数组切⽚.png)

## 布尔型索引
#### p133

In [41]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
names
data

In [42]:
names == "Bob"

In [43]:
data[names == "Bob"]

* 注意：如果布尔型数组的⻓度不对，布尔型选择就会出错，
因此⼀定要⼩⼼。

In [44]:
data[names == "Bob", 1:]
data[names == "Bob", 1]

In [45]:
names != "Bob"
~(names == "Bob")
data[~(names == "Bob")]

In [46]:
cond = names == "Bob"
data[~cond]

* 注意：Python关键字and和or在布尔型数组中⽆效。要是⽤&与|。
* 通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回⼀模⼀样的数组也是如此。


In [47]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

In [48]:
data[data < 0] = 0
data

In [49]:
data[names != "Joe"] = 7
data

## 花式索引
#### p137
* 花式索引是 NumPy 中一种通过整数数组或布尔数组从原数组中提取、修改或重组数据的强大方式。与普通切片不同，
* 它允许非连续、重复或任意顺序的索引操作，但总是返回数据的副本而非视图。

In [50]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

In [51]:
arr[[4, 3, 0, 6]]

In [52]:
arr[[-3, -5, -7]]

In [53]:
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [54]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [55]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

## 数组转置和轴对换
#### p139

In [56]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [3]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [5]:
arr.T @ arr
# 等效于np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [59]:
arr
arr.swapaxes(0, 1)

* 功能：randn = standard_normal 的快捷方式。

In [60]:
samples = np.random.standard_normal(size=(4, 4))
samples

In [10]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))

In [3]:
type(rng)

numpy.random._generator.Generator

## 通⽤函数：快速的元素级数组函数
#### p141

In [64]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

In [65]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x
y
np.maximum(x, y)

In [66]:
arr = rng.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

![表4_3_一元函数](./表4_3_一元函数.png)

![表4_4_二元函数](./表4_4_二元函数.png)

In [67]:
arr
out = np.zeros_like(arr)
np.add(arr, 1)
np.add(arr, 1, out=out)
out

## 利⽤数组进⾏数据处理
#### p145

In [68]:
points = np.arange(-5, 5, 0.01) # 100 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [69]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [71]:
plt.draw()

In [72]:
plt.close("all")

## 将条件逻辑表述为数组运算
#### p147

In [73]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [74]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [75]:
result = np.where(cond, xarr, yarr)
result

In [76]:
arr = rng.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

In [77]:
np.where(arr > 0, 2, arr) # set only positive values to 2

## 数学和统计⽅法
#### p149

In [78]:
arr = rng.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

In [79]:
arr.mean(axis=1)
arr.sum(axis=0)

In [80]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [81]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [82]:
arr.cumsum(axis=0)
arr.cumsum(axis=1)

![表4-5_基本数组统计方法](表4-5_基本数组统计方法.png)

## ⽤于布尔型数组的⽅法
#### p152

In [83]:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr <= 0).sum() # Number of non-positive values

In [84]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

## 排序
#### p152

In [85]:
arr = rng.standard_normal(6)
arr
arr.sort()
arr

In [86]:
arr = rng.standard_normal((5, 3))
arr

In [87]:
arr.sort(axis=0)
arr
arr.sort(axis=1)
arr

* 顶级⽅法np.sort返回的是数组的已排序副本，⽽就地排序则会修改数组本身。

In [88]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
sorted_arr2

## 唯⼀化以及其它的集合逻辑
#### p154

In [89]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [90]:
sorted(set(names))

In [2]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

![表4-6_数组的集合运算](表4-6_数组的集合运算.png)

## ⽤于数组的⽂件输⼊输出
#### p155

In [3]:
arr = np.arange(10)
np.save("some_array", arr)

In [4]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.savez("array_archive.npz", a=arr, b=arr)

In [95]:
arch = np.load("array_archive.npz")
arch["b"]

In [6]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)
#np.savez_compressed() 会将多个 NumPy 数组保存成一个 .npz 文件，并使用 ZIP 压缩算法对内容进行压缩。

In [97]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

## 线性代数
#### p156

In [7]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [99]:
np.dot(x, y)

In [8]:
x @ np.ones(3)
# np.ones(3) 创建一个包含 3 个元素的数组，所有值都是 1.0（浮点型）

array([ 6., 15.])

In [12]:
from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))
mat = X.T @ X
inv(mat)
# 取逆
mat @ inv(mat)
q, r = qr(mat)
# QR 分解：将矩阵 mat 分解成 Q 和 R，其中
# Q 是正交矩阵（列向量两两正交，Q.T @ Q = I）
# R 是上三角矩阵

![表4-7常⽤线性代数函数](表4-7常⽤线性代数函数.png)

## 伪随机数⽣成
#### p159

* normalvariate(mu, sigma) 用于生成符合正态分布（高斯分布）的单个随机数，参数 mu 是均值，sigma 是标准差。

In [61]:
from random import normalvariate  
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)

![表4-8部分numpy.random函数](表4-8部分numpy.random函数.png)

## 随机漫步
#### p161

In [102]:
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)


In [103]:
plt.figure()

In [104]:
plt.plot(walk[:100])

In [18]:
nsteps = 1000
rng = np.random.default_rng(seed=12345)  # fresh random generator
draws = rng.integers(0, 2, size=nsteps)
steps = np.where(draws == 0, 1, -1)
walk = steps.cumsum()

In [106]:
walk.min()
walk.max()

In [19]:
np.abs(walk) >= 10

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [20]:
(np.abs(walk) >= 10).argmax()

155

## ⼀次模拟多个随机漫步
#### p163

In [13]:
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks

array([[  1,   0,   1, ..., -44, -45, -44],
       [  1,   2,   1, ...,  10,  11,  10],
       [ -1,  -2,  -1, ..., -26, -25, -24],
       ...,
       [ -1,  -2,  -1, ...,  44,  45,  44],
       [  1,   0,   1, ..., -12, -11, -10],
       [  1,   0,   1, ...,  12,  11,  10]])

In [109]:
walks.max()
walks.min()

In [14]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30
hits30.sum() # Number that hit 30 or -30

3391

In [17]:
np.abs(walks)>= 30

array([[False, False, False, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [15]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
#.argmax(axis=1)
# 对每条路径，找出第一次为 True 的索引（也就是第一次到达 ±30 的时刻）
# 因为 argmax 返回的是第一个最大值（对于布尔值来说就是第一个 True）
crossing_times

array([601, 237, 451, ..., 317, 125, 137], dtype=int64)

In [112]:
crossing_times.mean()

In [113]:
draws = 0.25 * rng.standard_normal((nwalks, nsteps))